### PR TITLE
Handling for SQL Server 2022 Version

### PR DESCRIPTION
**Pull request by benjimac93**
Nice simple one :)

### CODE REVIEW

**Comment by NickCraver** [comment]
@benjimac93 if you know the details, would you mind including `src/Opserver.Core/Data/SQL/SQLServerEngine.cs` as well here please? If not no worries, can grab when off mobile :)

**Comment by benjimac93** [comment]
Sure can. Will sort this today !

**Comment by benjimac93** [comment]
Added. Didn't add any of the CU's as they're not there for previous versions and adding didn't appear to change any functionality.

**Review by NickCraver — APPROVED** [review]
👍 Thank you!

**Comment by NickCraver** [comment]
Thank you sir! <3

**Pull request merged**
