### PR TITLE
Added button for Take Down in HAproxy

### PR DESCRIPTION
**Pull request by surgicalcoder**
Added a button alongside the other two buttons for HAProxy Admins, to take "down" a server, via Maint.

### CODE REVIEW

**Comment by NickCraver** [comment]
Serious question: what's the use case over DRAIN? We switched to DRAIN a while ago because the assumed-up rather than assumed-down behavior when moving to ENABLE was always undesirable - can you elaborate on where this isn't the case?

I'm not against more behaviors, but I am against this *specific* approach. If this behavior is actually desired, I'm thinking either a config option or a gear menu like redis over n buttons.

**Comment by surgicalcoder** [comment]
Our experience has been with DRAIN, existing connections still go through to the same server, and we have to use sticky sessions (part of our application is legacy, like Classic ASP 2.0 legacy). With sticky sessions and DRAIN, connections still go through to the server (albeit "existing" ones that have sticky cookies) - whereas with MAINT, it boots everyone off, overriding their stickyness.

With the gear menu - are you thinking of that replacing all buttons e.g. up and down, replacing the down, or alongside the up and down - e.g. Up, Down, gear menu ?

**Comment by NickCraver** [comment]
@surgicalcoder probably up/down/gear, but I'll honestly have to play with it. The gear could contain all of the available actions and disable what doesn't make sense. For example things like enabling/disabling health checks would also be in there. [You can view the available actions in the HAProxy code here](https://github.com/haproxy/haproxy/blob/55c6d8a5a1ea8006c79e1122c2de338f20df2d74/src/dumpstats.c#L100).

**Comment by NickCraver** [comment]
Check out the latest overhaul branch - I added some goodness around HAProxy fine-grained control that also includes health checks, killing sessions, etc. I'm closing this out just to clean up but I hope it covers all your use cases! If not, please ping me here.

**Pull request closed without merging**
