### PR TITLE
Added null-check for Jira-settings in Exceptions.Detail

### PR DESCRIPTION
**Pull request by itssimple**
#204

### CODE REVIEW

**Comment by NickCraver** [comment]
I'll merge this in after the current exceptions work is done (working on it this week). Note: you can now do: `Current.Settings.Jira?.Enabled` in C# 6 (I can update this after merge).

**Comment by itssimple** [comment]
Right.. I didn't think of that. Thanks for reminding me!


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Nick Craver <notifications@github.com> Date: 26/07/2016  18:49  (GMT+01:00) To: opserver/Opserver <Opserver@noreply.github.com> Cc: Chris <webmaster@itssimple.se>, Author <author@noreply.github.com> Subject: Re: [opserver/Opserver] Added null-check for Jira-settings in Exceptions.Detail (#205) 
I'll merge this in after the current exceptions work is done (working on it this week). Note: you can now do: Current.Settings.Jira?.Enabled in C# 6 (I can update this after merge).

**Comment by NickCraver** [comment]
What is the bosun provider change in the other commit?

**Comment by itssimple** [comment]
It wasn’t supposed to get into the pull request, must’ve happened while committing to my local repo.

It’s to make servers that doesn’t have a ICMP-collection, show as Active, instead of Unreachable.

 

Without the check for any records, it returns true, which results in Unreachable, even though the data is there.

 

Regards,

Chris Gårdenberg

 <http://itssimple.se/> It’s Simple Studios

 

Från: Nick Craver [mailto:notifications@github.com] 
Skickat: den 27 juli 2016 22:20
Till: opserver/Opserver <Opserver@noreply.github.com>
Kopia: Chris Gårdenberg <webmaster@itssimple.se>; Author <author@noreply.github.com>
Ämne: Re: [opserver/Opserver] Added null-check for Jira-settings in Exceptions.Detail (#205)

 

What is the bosun provider change in the other commit?

**Comment by NickCraver** [comment]
Thanks!

**Pull request merged**
