### PR TITLE
Security config example include ad authentication. SQLInstance.Databases.cs group

### PR DESCRIPTION
**Pull request by lmchao**
Included user and password parameters in security config example
Modified FetchSQL2012Joins to group by database. With out this there where duplicate databases wher more than one file.

### CODE REVIEW

**Comment by NickCraver** [comment]
The AD example doesn't have usernames or password because in a proper environment the intent is that you don't need them. I'm okay adding *another* example and stating why they'd be needed, but by default you're querying AD as the service account running the application pool - so you don't need any credentials stored in the config.

**Comment by lmchao** [comment]
If the default behaviour is that it uses the app pool user then there is something that didn't work in my environment. I have same user in config and app pool but if I remove it from config file I loose AD login.
In fact it would be better not to save the credentials in the config file as you state.

My bad, but there is another change in this commit: Modified FetchSQL2012Joins to group by database. Without this there were duplicate databases where more than one file.

**Comment by NickCraver** [comment]
@lmchao Sorry I dropped the ball here - can you please submit a pull request with *only* the database change so I can merge it in?

**Comment by NickCraver** [comment]
Closing this out to cleanup - *please* send a PR with only the SQL changes, I'll happily merge it in.

**Pull request closed without merging**
