### PR TITLE
Create issues on Jira from Exception details page

### PR DESCRIPTION
**Pull request by aliozgur**
Hi,
I've extended OpServer so that we can create Jira issues using the links rendered on Exception details page. Jira functionality and links are defined in  JiraSettings.json config file.

Here are some [screnshots](http://imgur.com/a/XtW0j)

### CODE REVIEW

**Comment by NickCraver** [comment]
Thanks for the request! This is awesome indeed.

Before accepting we need to make a few fixes though, I'll enumerate here and happy to explain further if needed:
 - IMO there's no need for the heavy REST client dependency - these are 2 simple web requests so just a `WebClient` will do - we're just not getting much out of that dependency load (and I'm unsure of its license but it may or may not be compatible)
 - The reference to Newtonsoft was changed, but no files were committed for either this or RestSharp, this would result in a broken build. I'd revert Newtonsoft to the 6.0.3 version it was at resulting in no changes to packages here. I have a push with all the refs updates in our internal repo and am working to eliminate Newtonsoft as well (in favor of a much faster Jil).
 - The `web.config` changes simple need to be reversed on the security groups (inadvertent commit?)
 - The IIS settings in the `.csproj` would break all other developers (including me), please revert the `<WebProjectProperties>` section changes. If you're on VS 2013 *before* Update 1 it'll save these changes to the `.csproj` instead of your uncommitted `.user` file locally - in Update 1 they added a checkbox back on the project properties to save it *not* in the `.csproj` which is what you want - that way anyone developing Opserver can choose their setup.

If any of these are ambiguous or you want more reasoning I'm happy to discuss or explain. I look forward to pulling this in, awesome work!

**Comment by aliozgur** [comment]
Hi @NickCraver,
* RestSharp has Apache License which I think is compatible with OpServer's MIT licences. But if that is not OK for you I can spend some time to replace RestSharp with WebClient. Just let me know
* Fixed (d8c38b2) This was a side effect of our own practice which is not to put packages under version control and use *restore packages*
* Fixed (d8c38b2), though this was an intetional change
* Fixed (d8c38b2), result of internal practice

**Comment by NickCraver** [comment]
Hi @aliozgur,

The concern was not the license of RestSharp - that was just a note. I am against pulling in a dependency that saves only a few lines of code here, it's just far from justified IMO. I would much rather you reverted the package changes here since none are necessary for this pull request overall.

The last few commits also caused more trouble with .csproj, it looks like you've included all the `.json` config files rather than just the `.example` files (which aren't included in source control, and shouldn't be). The net diff should just be your additional file includes there.

Thanks!

**Comment by aliozgur** [comment]
Hi @NickCraver,
I guess with 96931ce and a6e692b all issues are fixed.

**Comment by NickCraver** [comment]
Hey @aliozgur,
Sorry for the delay - I was prepping the rest of our internal changes and updating Github with all the PagerDuty bits and such added lately. I see most issues resolved in those commits but I still see the `web.config` which has massive changes to whitespace but no effective changes (just revert?) and the similar for Exceptions.Detail.cshtml - can you scope that back to only what was added? The whitespace is also intentionally the way it is for the output consistency of HTML which razor isn't awesome at. With the changes in Exceptions.Details.Html, I'd also wrap the Partial for Jira actions in a `.Enabled` check, there's no need to even fire up the view engine for anyone not using it.

The last item I'm confused about is "Issues" with Jira - I see them called issues in the config/settings, but "actions" elsewhere. It would be far clearer to me to simply call them "actions" in both places - since Issues has an exact terminology in Jira that we'd be conflicting with anyway...or am I missing something different here? Admittedly I haven't used Jira in some time so maybe things have changes there.

I was hoping there wouldn't be a conflict with the changes, but I imagine the project file updates are throwing the pull request off. A rebase on master would be most appreciated, but I can merge in manually if it gives any trouble.

Thanks!

**Comment by aliozgur** [comment]
@NickCraver 
I will fix the last bits probably tomorrow. 
I will also try to rebase on master and see what happens.

**Comment by aliozgur** [comment]
Hi @NickCraver ,
I tried to rebase but the csproj caused too much headache. I can spend some more time for rebase.

**Comment by aliozgur** [comment]
Hi @NickCraver,
I tried rebase and csproj files are messed up. I will close this pull request and create a new one

**Comment by aliozgur** [comment]
See #78

**Pull request closed without merging**
