### PR TITLE
Fix GetNodesByIP when one data provider is present

### PR DESCRIPTION
**Pull request by jvitkauskas**
Fix a simple typo: should check if list contains one element (not zero) when accessing first one.

### CODE REVIEW

**Comment by kshyju** [comment]
I guess `Any()` would return `true` when it sees the first item  where `Count` will count all the items.

**Comment by georgeduckett** [comment]
@kshyju It would also return true for more than one, which we don't want. `_dataProviders` is a list so it can just read the property; it doesn't have to enumerate anything anyway.

**Comment by jvitkauskas** [comment]
Actually, there were similar fixes before:
https://github.com/opserver/Opserver/commit/483d18ff68da3b9d849276cfdb994b3849d1a51b#diff-ae5251f9f889b382d8ce197549b695d4L49

So this one is not new.

**Comment by NickCraver** [comment]
Apologies on the delay, I was getting the async overhaul merged in - thanks for this fix!

**Pull request merged**
