### PR TITLE
Add support for new perNodeSetting called "description".  

### PR DESCRIPTION
**Pull request by KennethScott**
Hey Nick, we've got quite a few nodes going on our opserver dashboard now and I've found myself sometimes wishing we had a way to display a brief description of the server(s) if needed.  I know you can argue the categories help, but even with several categories, sometimes it's nice to just have a quick description about the node.

This small change is my attempt at supporting that.  I basically just added a new "description" property in the perNodeSettings that when present, will be prepended onto the title attribute and displayed on hover along with the existing text:

image

Please take a look and let me know your thoughts.  Thanks!

### CODE REVIEW

**Comment by KennethScott** [comment]
Hello @NickCraver, any interest in this?  Thanks-

**Comment by KennethScott** [comment]
ZZzzzzzz....

**Comment by NickCraver** [comment]
I'm not against a setting perse, but having one only for a tooltip seems a bit odd - I'm just not sure it makes much sense. Implementation wise: this creates a new collection and a lot of strings per row render, it needs to just render if present and skip if not instead (e.g. a ternary). More to the first point though: wouldn't this be something displayed on the node's page? If so, we should look at how this implements across providers (e.g. Bosun and/or Orion).

**Comment by nickluu2018** [comment]
The description does not display as expected

**Pull request closed without merging**
