### PR TITLE
Feature implementation: Create Jira issues from Exception Details page

### PR DESCRIPTION
**Pull request by aliozgur**
Hi @NickCraver ,
This is the new pull request. Hopefully this time you will be able to auto merge.

### CODE REVIEW

**Comment by aliozgur** [comment]
This is the ready to merge version of pull request #77

**Comment by NickCraver** [comment]
Thanks @aliozgur, I've been out a few days but will try and pull/test/merge this today - browsing it looks great. Thanks a lot for fixing all issues so quickly!

**Comment by NickCraver** [comment]
Merged in - I'll make a few optimization tweaks, but looks good already. Thanks!

**Comment by aliozgur** [comment]
Great @NickCraver.
I plan to start working on some veeamone fatures if i can find spare time.

**Pull request merged**
