### PR TITLE
Fixed a javascript error when server culture uses comma as separator

### PR DESCRIPTION
**Pull request by smurariu2**
Naive fix, i know but Nullable.ToString does not take any arguments hence it was not possible to send InvariantCulture without complicating the code a lot

### CODE REVIEW

**Comment by latop2604** [comment]
You should use `?.ToString(CultureInfo.InvariantCulture)` instead of `.ToString().Replace(',','.')`

**Comment by latop2604** [comment]
Same issue in  /Views/Dashboard/Node.Stats.cshtml

**Comment by smurariu2** [comment]
thank you. 
updated.

**Comment by NickCraver** [comment]
thanks! will fix up these includes in another commit since it's in a few places now.

**Comment by smurariu2** [comment]
glad i could help

**Pull request merged**
