### PR TITLE
Fix Jira API response Json Deserialize

### PR DESCRIPTION
**Pull request by rducom**
The Jira API changed. I updated the `JiraCreateIssueResponse` poco accordingly.

### CODE REVIEW

**Comment by NickCraver** [comment]
@rducom can you please elaborate? If it changed, wouldn't this break users on older versions of JIRA?

**Comment by NickCraver** [comment]
@rducom Any info on the above? I don't use JIRA, but I'd assume we have to support both versions here.

**Comment by rducom** [comment]
Since Jira is an online AND on premise, if a Jira on premise customer didn't update his version, there are chances it will break. I can only guarantee this fix applies to the online version (we don't use it on premise)

**Comment by NickCraver** [comment]
I'm alright with just changing it, but let's keep the C# as C# conventions. 

For example, instead of this:
```c#
public string key { get; set; }
```
Do this:
```c#
[DataMember(Name="key")]
public string Key { get; set; }
```

**Pull request merged**
