### PR TITLE
Fix Microsoft.WebApplication.targets path

### PR DESCRIPTION
**Pull request by rducom**
Issue : Unable to use VS2k17 publish feature.
This fix Microsoft.WebApplication.targets path in csproj

### CODE REVIEW

**Comment by NickCraver** [comment]
The current path is intentional, as it bypasses the requirement of needing full web application targets install on the build server for what amounts to a < 70KB `.dll` and `.targets` pair.

What are you hitting with the deploy in VS 2017?

**Comment by rducom** [comment]
I'm hitting the folowing error : 
The target "GatherAllFilesToPublish" does not exist in the project.

**Comment by mqbk** [comment]
how did you correct this error? I am getting the same thing.

**Comment by NickCraver** [comment]
Finally found time to fix our build agents (lacking the proper web workloads), merging in - and thanks for the reminder!

**Pull request merged**
