### PR TITLE
Added Service Tag/Serial Number to WMI

### PR DESCRIPTION
**Pull request by jeddytier4**
Added service tag lookup for DELL physical servers for WMI polling.

### CODE REVIEW

**Comment by NickCraver** [comment]
I'm not against this - I'm all for it, but shouldn't this work for many more vendors? Can we check for it in a more generic way that's unrestricted? 

@afscrome thoughts?

**Comment by afscrome** [comment]
`win32_bios` has a `SerialNumber` property which looks like it should be more generic.  At least it works for me on both a Lenovo laptop and a Dell laptop.  

```ps
Get-WmiObject win32_bios


SMBIOSBIOSVersion : 1.1.3
Manufacturer      : Dell Inc.
Name              : 1.1.3
SerialNumber      : REMOVED
Version           : DELL   - 1072009
```

**Comment by jeddytier4** [comment]
Agreed, will update the pull request to change Service Tag to serialnumber.  That field exists for all servers, but is very long on VMs.  i.e. VMware-## ## ## ## ## ## ## ##-## ## ## ## ## ## ## ## that is the serial number of a VMWare vm, and ####-####-####-####-####-####-#### on Hyper-V.  Am looking into using something like SELECT * FROM Win32_ComputerSystem  WHERE Model LIKE '%Virtual%' to filter them out for now.

**Comment by NickCraver** [comment]
I'd pull that long field as-is in WMI, and we can filter it in code. We could for example have a SerialNumberDetail available on hover that we split it into on `Node` or something.

**Comment by jeddytier4** [comment]
I have updated it to pull the Service Tag/Serial Number from Win32_BIOS.  The virtual machines' serial numbers actually look ok in the UI as is, but I'm UI dysfunctional, so someone with a better eye should probably look at it.

**Comment by NickCraver** [comment]
Thanks!

**Pull request merged**
